# Generated by Django 4.1.7 on 2023-02-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sort',
            field=models.TextField(default=1, max_length=130),
            preserve_default=False,
        ),
    ]
